name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up deployment environment
        run: |
          echo "Setting up deployment environment..."
          mkdir -p css js images data
          touch .nojekyll
          
          # Debug: Show current directory structure
          echo "Current directory structure:"
          ls -la
          
          # Debug: Show contents of each directory
          echo "Contents of directories:"
          for dir in css js images data; do
            echo "Contents of $dir/:"
            ls -la $dir/ || echo "$dir is empty"
          done

      - name: Copy files to deployment locations
        run: |
          echo "Copying files to deployment locations..."
          
          # Copy HTML files
          echo "Copying HTML files..."
          cp -v index.html results.html ./
          
          # Copy CSS files
          echo "Copying CSS files..."
          cp -v css/style.css css/
          
          # Copy JS files
          echo "Copying JS files..."
          cp -v js/*.js js/
          
          # Copy images
          echo "Copying images..."
          cp -v images/* images/ || true
          
          # Copy data files
          echo "Copying data files..."
          cp -v data/*.csv data/ || true
          
          # Debug: Show final structure
          echo "Final directory structure:"
          ls -R

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
          clean-exclude: |
            .nojekyll
            .gitignore
          single-commit: true

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          git checkout gh-pages
          echo "Files in gh-pages branch:"
          ls -la
          echo "Complete directory structure:"
          ls -R
          
          # Check for critical files
          for file in index.html results.html css/style.css js/data.js; do
            if [ -f "$file" ]; then
              echo "✓ Found $file"
            else
              echo "✗ Missing $file"
            fi
          done
