name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean build directory
        run: |
          rm -rf build
          mkdir -p build

      - name: Copy project files
        run: |
          # Create directory structure
          mkdir -p build/{js,css,images,data}

          # Copy files with absolute paths and set permissions
          cp index.html build/
          cp -r js/* build/js/
          cp -r css/* build/css/
          cp -r images/* build/images/ || true
          
          # Explicitly copy data files
          echo "Copying data files..."
          cp data/*.csv build/data/

          # Set permissions
          chmod -R 644 build/data/*.csv
          chmod -R 644 build/css/*.css
          find build -type d -exec chmod 755 {} \;

          # Verify data files
          echo "Verifying data files..."
          ls -la build/data/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true

      - name: Verify deployment
        run: |
          echo "Deployment complete. Build directory contents:"
          find build -type f
