name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository contents before copy
        run: |
          echo "Repository contents:"
          ls -la
          echo "Data directory contents:"
          ls -la data/

      - name: Setup deployment
        run: |
          # Create all required directories
          mkdir -p build/data
          mkdir -p build/js
          mkdir -p build/css
          mkdir -p build/images

          # Copy files with verbose output
          echo "Copying HTML files..."
          cp -v index.html build/
          cp -v results.html build/ || true

          echo "Copying JavaScript files..."
          cp -rv js/* build/js/

          echo "Copying CSS files..."
          cp -rv css/* build/css/

          echo "Copying image files..."
          cp -rv images/* build/images/ || true

          echo "Copying data files..."
          cp -v data/*.csv build/data/

          echo "Build directory structure after copy:"
          find build -type f

      - name: Verify data files
        run: |
          echo "Checking data files in build directory..."
          ls -la build/data/
          
          if [ ! -f "build/data/existing_upgs_updated.csv" ]; then
            echo "ERROR: existing_upgs_updated.csv is missing!"
            exit 1
          fi
          
          if [ ! -f "build/data/updated_uupg.csv" ]; then
            echo "ERROR: updated_uupg.csv is missing!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
